/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaLesson1.Views;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author mac
 */
public class DashboardFrame extends javax.swing.JFrame {

    private final int[] hoverColor;
    private final JPanel[] listMenu;
    private boolean menuIsOpen;
    private int mousepX;
    private int mousepY;
    /**
     * Creates new form DashboardFrame
     */
    public DashboardFrame() {
        initComponents();
        hoverColor = new int[] {0,51,102};
        listMenu = new JPanel[] {BtnToggle, BtnSetting};
        menuIsOpen = true;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        IconWindow = new javax.swing.JPanel();
        BtnMin = new javax.swing.JPanel();
        BtnMax = new javax.swing.JPanel();
        BtnMaxIcon = new javax.swing.JLabel();
        BtnClose = new javax.swing.JPanel();
        BtnCloseIcon = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        MenuIcons = new javax.swing.JPanel();
        BtnToggle = new javax.swing.JPanel();
        BtnToggleIcon = new javax.swing.JLabel();
        BtnSetting = new javax.swing.JPanel();
        BtnSettingIcon = new javax.swing.JLabel();
        MenuHide = new javax.swing.JPanel();
        Dashboard = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 600));

        Header.setBackground(new java.awt.Color(2, 37, 72));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });
        Header.setLayout(new java.awt.BorderLayout());

        IconWindow.setBackground(new java.awt.Color(2, 37, 72));
        IconWindow.setPreferredSize(new java.awt.Dimension(150, 50));
        IconWindow.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 0));

        BtnMin.setBackground(new java.awt.Color(2, 37, 72));
        BtnMin.setPreferredSize(new java.awt.Dimension(50, 100));
        BtnMin.setLayout(new java.awt.BorderLayout());
        IconWindow.add(BtnMin);

        BtnMax.setBackground(new java.awt.Color(2, 37, 72));
        BtnMax.setPreferredSize(new java.awt.Dimension(50, 100));
        BtnMax.setLayout(new java.awt.BorderLayout());

        BtnMaxIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnMaxIcon.setIcon(new javax.swing.ImageIcon("/Users/mac/NetBeansProjects/javaLesson1/src/main/java/Icon/full_screen_32px.png")); // NOI18N
        BtnMaxIcon.setPreferredSize(new java.awt.Dimension(84, 48));
        BtnMaxIcon.setSize(new java.awt.Dimension(40, 40));
        BtnMaxIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMaxIconMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnMaxIconMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnMaxIconMouseEntered(evt);
            }
        });
        BtnMax.add(BtnMaxIcon, java.awt.BorderLayout.PAGE_START);

        IconWindow.add(BtnMax);

        BtnClose.setBackground(new java.awt.Color(2, 37, 72));
        BtnClose.setPreferredSize(new java.awt.Dimension(50, 100));
        BtnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCloseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnCloseMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnCloseMouseEntered(evt);
            }
        });
        BtnClose.setLayout(new java.awt.BorderLayout());

        BtnCloseIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnCloseIcon.setIcon(new javax.swing.ImageIcon("/Users/mac/NetBeansProjects/javaLesson1/src/main/java/Icon/delete_32px.png")); // NOI18N
        BtnCloseIcon.setPreferredSize(new java.awt.Dimension(84, 48));
        BtnCloseIcon.setSize(new java.awt.Dimension(40, 40));
        BtnCloseIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCloseIconMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnCloseIconMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnCloseIconMouseEntered(evt);
            }
        });
        BtnClose.add(BtnCloseIcon, java.awt.BorderLayout.PAGE_START);

        IconWindow.add(BtnClose);

        Header.add(IconWindow, java.awt.BorderLayout.LINE_END);

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setPreferredSize(new java.awt.Dimension(210, 333));
        Menu.setLayout(new java.awt.BorderLayout());

        MenuIcons.setBackground(new java.awt.Color(2, 37, 72));
        MenuIcons.setAlignmentX(0.0F);
        MenuIcons.setPreferredSize(new java.awt.Dimension(50, 345));
        MenuIcons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        BtnToggle.setBackground(new java.awt.Color(2, 37, 72));
        BtnToggle.setPreferredSize(new java.awt.Dimension(50, 50));
        BtnToggle.setLayout(new java.awt.BorderLayout());

        BtnToggleIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnToggleIcon.setIcon(new javax.swing.ImageIcon("/Users/mac/NetBeansProjects/javaLesson1/src/main/java/Icon/back_32px.png")); // NOI18N
        BtnToggleIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnToggleIconMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnToggleIconMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnToggleIconMouseEntered(evt);
            }
        });
        BtnToggle.add(BtnToggleIcon, java.awt.BorderLayout.CENTER);

        MenuIcons.add(BtnToggle);

        BtnSetting.setBackground(new java.awt.Color(2, 37, 72));
        BtnSetting.setPreferredSize(new java.awt.Dimension(50, 50));
        BtnSetting.setLayout(new java.awt.BorderLayout());

        BtnSettingIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnSettingIcon.setIcon(new javax.swing.ImageIcon("/Users/mac/NetBeansProjects/javaLesson1/src/main/java/Icon/settings_32px.png")); // NOI18N
        BtnSettingIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSettingIconMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnSettingIconMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnSettingIconMouseEntered(evt);
            }
        });
        BtnSetting.add(BtnSettingIcon, java.awt.BorderLayout.CENTER);

        MenuIcons.add(BtnSetting);

        Menu.add(MenuIcons, java.awt.BorderLayout.LINE_START);

        MenuHide.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout MenuHideLayout = new javax.swing.GroupLayout(MenuHide);
        MenuHide.setLayout(MenuHideLayout);
        MenuHideLayout.setHorizontalGroup(
            MenuHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        MenuHideLayout.setVerticalGroup(
            MenuHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        Menu.add(MenuHide, java.awt.BorderLayout.CENTER);

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        Dashboard.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout DashboardLayout = new javax.swing.GroupLayout(Dashboard);
        Dashboard.setLayout(DashboardLayout);
        DashboardLayout.setHorizontalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );
        DashboardLayout.setVerticalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        getContentPane().add(Dashboard, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void changeColor(javax.swing.JPanel hover, java.awt.Color rand) {
        hover.setBackground(rand);
    }
    
    public void openMenu(javax.swing.JPanel myPanel) {
        for (int i = 0; i < listMenu.length; i++) {
            JPanel jPanel = listMenu[i];
            changeColor(jPanel, new Color(2,37,72));
        }
        changeColor(myPanel, new Color(hoverColor[0], hoverColor[1], hoverColor[2]));
    }
    
    public void mouseInMenu(javax.swing.JPanel myPanel) {
        myPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 0, 0, new java.awt.Color(51, 153, 255)));
    }
    
    public void mouseOutMenu(javax.swing.JPanel myPanel) {
        myPanel.setBorder(null);
    }
    
    public void toggleMenu() {
        if (menuIsOpen) {
            Menu.setPreferredSize(new Dimension(210, Menu.getHeight()));
            BtnToggleIcon.setIcon(new javax.swing.ImageIcon("/Users/mac/NetBeansProjects/javaLesson1/src/main/java/Icon/back_32px.png"));
        } else {
            Menu.setPreferredSize(new Dimension(50, Menu.getHeight()));
            BtnToggleIcon.setIcon(new javax.swing.ImageIcon("/Users/mac/NetBeansProjects/javaLesson1/src/main/java/Icon/menu_32px.png"));
        }
        SwingUtilities.updateComponentTreeUI(Menu);
    }
    
    private void BtnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCloseMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCloseMouseEntered

    private void BtnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCloseMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCloseMouseExited

    private void BtnCloseIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCloseIconMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BtnCloseIconMouseClicked

    private void BtnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCloseMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCloseMouseClicked

    private void BtnCloseIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCloseIconMouseEntered
        // TODO add your handling code here:
        changeColor(BtnClose, new Color(hoverColor[0], hoverColor[1], hoverColor[2]));
    }//GEN-LAST:event_BtnCloseIconMouseEntered

    private void BtnCloseIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCloseIconMouseExited
        // TODO add your handling code here:
        changeColor(BtnClose, new Color(2,37,72));
    }//GEN-LAST:event_BtnCloseIconMouseExited

    private void BtnMaxIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMaxIconMouseClicked
        // TODO add your handling code here:
        if (this.getExtendedState() != DashboardFrame.MAXIMIZED_BOTH) {
            this.setExtendedState(DashboardFrame.MAXIMIZED_BOTH);
        } else {
            this.setExtendedState(DashboardFrame.NORMAL);
        }
    }//GEN-LAST:event_BtnMaxIconMouseClicked

    private void BtnMaxIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMaxIconMouseEntered
        // TODO add your handling code here:
        changeColor(BtnMax, new Color(hoverColor[0], hoverColor[1], hoverColor[2]));
    }//GEN-LAST:event_BtnMaxIconMouseEntered

    private void BtnMaxIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMaxIconMouseExited
        // TODO add your handling code here:
        changeColor(BtnMax, new Color(2,37,72));
    }//GEN-LAST:event_BtnMaxIconMouseExited

    private void BtnToggleIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnToggleIconMouseClicked
        // TODO add your handling code here:
        openMenu(BtnToggle);
        menuIsOpen = !menuIsOpen;
        toggleMenu();
    }//GEN-LAST:event_BtnToggleIconMouseClicked

    private void BtnToggleIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnToggleIconMouseEntered
        // TODO add your handling code here:
        mouseInMenu(BtnToggle);
    }//GEN-LAST:event_BtnToggleIconMouseEntered

    private void BtnToggleIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnToggleIconMouseExited
        // TODO add your handling code here:
        mouseOutMenu(BtnToggle);
    }//GEN-LAST:event_BtnToggleIconMouseExited

    private void BtnSettingIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSettingIconMouseClicked
        // TODO add your handling code here:
        openMenu(BtnSetting);
    }//GEN-LAST:event_BtnSettingIconMouseClicked

    private void BtnSettingIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSettingIconMouseEntered
        // TODO add your handling code here:
        mouseInMenu(BtnSetting);
    }//GEN-LAST:event_BtnSettingIconMouseEntered

    private void BtnSettingIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSettingIconMouseExited
        // TODO add your handling code here:
        mouseOutMenu(BtnSetting);
    }//GEN-LAST:event_BtnSettingIconMouseExited

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        // TODO add your handling code here:
        int cordinatX = evt.getXOnScreen();
        int cordinatY = evt.getYOnScreen();
        
        setLocation(cordinatX - mousepX, cordinatY - mousepY);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        // TODO add your handling code here:
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardFrame().setVisible(true);
//               ComponentMover(frame, Header);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnClose;
    private javax.swing.JLabel BtnCloseIcon;
    private javax.swing.JPanel BtnMax;
    private javax.swing.JLabel BtnMaxIcon;
    private javax.swing.JPanel BtnMin;
    private javax.swing.JPanel BtnSetting;
    private javax.swing.JLabel BtnSettingIcon;
    private javax.swing.JPanel BtnToggle;
    private javax.swing.JLabel BtnToggleIcon;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel IconWindow;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel MenuHide;
    private javax.swing.JPanel MenuIcons;
    // End of variables declaration//GEN-END:variables
}
