/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaLesson1.Views;

/**
 *
 * @author mac
 */
public class LayoutFrame extends javax.swing.JFrame {

    /**
     * Creates new form LayoutFrame
     */
    public LayoutFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sidebar = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        TitleDashboard = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        HeaderItems = new javax.swing.JPanel();
        HeaderItem1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        HeaderItem2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        Sidebar.setBackground(new java.awt.Color(44, 61, 79));
        Sidebar.setPreferredSize(new java.awt.Dimension(90, 100));
        getContentPane().add(Sidebar, java.awt.BorderLayout.LINE_START);

        Header.setBackground(new java.awt.Color(99, 110, 114));
        Header.setPreferredSize(new java.awt.Dimension(100, 40));
        Header.setLayout(new java.awt.BorderLayout());

        TitleDashboard.setBackground(new java.awt.Color(44, 61, 79));
        TitleDashboard.setPreferredSize(new java.awt.Dimension(90, 100));

        jLabel3.setText("Dashboard");
        TitleDashboard.add(jLabel3);

        Header.add(TitleDashboard, java.awt.BorderLayout.LINE_START);

        HeaderItems.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 0));

        HeaderItem1.setPreferredSize(new java.awt.Dimension(150, 40));
        HeaderItem1.setRequestFocusEnabled(false);

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Search");
        jTextField1.setPreferredSize(new java.awt.Dimension(100, 23));
        jTextField1.setSize(new java.awt.Dimension(90, 90));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        HeaderItem1.add(jTextField1);

        HeaderItems.add(HeaderItem1);

        HeaderItem2.setPreferredSize(new java.awt.Dimension(200, 40));
        HeaderItem2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel1.setText("Admin");
        HeaderItem2.add(jLabel1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/mac/NetBeansProjects/javaLesson1/src/main/java/Icon/account_circle.png")); // NOI18N
        jLabel2.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jLabel2.setPreferredSize(new java.awt.Dimension(30, 30));
        HeaderItem2.add(jLabel2);

        HeaderItems.add(HeaderItem2);

        Header.add(HeaderItems, java.awt.BorderLayout.CENTER);

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(223, 230, 233));
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LayoutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LayoutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LayoutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LayoutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LayoutFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel HeaderItem1;
    private javax.swing.JPanel HeaderItem2;
    private javax.swing.JPanel HeaderItems;
    private javax.swing.JPanel Sidebar;
    private javax.swing.JPanel TitleDashboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
